BookRecommend/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from .sitempas import StaticSitemap, celebritySitemap, bookSitemap, authorSitemap, seriesSitemap, subCategoriesSitemap

dynamic = {
    'celebrity': celebritySitemap,
    'book': bookSitemap,
}
sitemaps = {'static': StaticSitemap,
            'celebrity': celebritySitemap,
            'book': bookSitemap,
            'author': authorSitemap,
            'series' : seriesSitemap,
            'subcategories' : subCategoriesSitemap
        }
urlpatterns = [
    path('admin-secrets@readrecommend/', admin.site.urls),
    path('', include('Books.urls')),
    path('people/', include('Celebrity.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Books/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/<str:keyword>', views.search, name='search'),
    path('global-search', views.globalSearch, name='global-search'),
    path('best-books-on-categories', views.categories, name='categories'),
    path('books-categories/best-books-on-<str:name>', views.subCategories, name='sub-categories'),
    path('series/', views.series, name='series'),
    path('filter-series', views.filterSeries, name="filter-series"),
    path('series/<str:name>-books-in-order', views.seriesDetail, name='series-detail'),
    path('about', views.about, name='about'),
    path('privacy-policy', views.privacyPolicy, name='privacy-policy'),
   
    path('contact-us', views.contact, name='contact'),
    path('api/subcategories/<str:category_id>', views.get_sub_category, name='subcategory_api'),
    path('filter-books', views.filterBooks, name="filter-books"),
    path('books', views.books, name='books'),
    path('books/<str:name>', views.bookDetail, name='book-detail'),
] 

Books/models.py
from django.db import models
from django.shortcuts import reverse
import os
from django.core.exceptions import ValidationError
from utils.common_function import slugify
from Celebrity.models import Celebrity

class Categories(models.Model):
    name = models.CharField(max_length=100,blank=False)
    name_slug = models.SlugField(blank=True, null=True, editable=False)

    def __str__(self):
        return f'{self.name}' 
    
    def save(self, *args, **kwargs):
        if self.name:
            self.name_slug = slugify(self.name.upper())
        if self.pk is None and Categories.objects.filter(name_slug=self.name_slug).exists():
            raise ValidationError("Name must be unique (case-insensitive).")
        super().save(*args, **kwargs)

class SubCategory(models.Model):
    name = models.CharField(max_length=100,blank=False)
    name_slug = models.SlugField(blank=True, null=True, editable=False)
    Category = models.ForeignKey(Categories, blank=True, null=True, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'{self.name}' 
    
    def save(self, *args, **kwargs):
        if self.name:
            self.name_slug = slugify(self.name.upper())
        super().save(*args, **kwargs)

def get_upload_series_path(instance, filename):
    field_value = instance.name
    # date_time = timezone.now().strftime('%Y/%m/%d')
    filename = os.path.basename(filename)
    return f'media/Series/{field_value}/{filename}'

class Series(models.Model):
    name = models.CharField(max_length=100,blank=True)
    name_slug = models.SlugField(blank=True, null=True, editable=False)
    title = models.CharField(max_length=256,blank=True)
    author_name = models.ForeignKey(Celebrity, null=True, on_delete=models.DO_NOTHING)
    description = models.TextField(null=True, blank=True)
    categories = models.ManyToManyField('Categories', blank=True)
    sub_categories = models.ManyToManyField('SubCategory', blank=True)
    ISBN = models.CharField(max_length=100,blank=True)
    image = models.FileField(upload_to=get_upload_series_path, blank=True)


    def __str__(self):
        return f'{self.name}' 
    
    def save(self, *args, **kwargs):
        if self.name:
            self.name_slug = slugify(self.name.upper())
        if self.pk is None and Series.objects.filter(name_slug=self.name_slug).exists():
            raise ValidationError("Name must be unique (case-insensitive).")
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        path = reverse('series-detail', args=[self.name_slug])
        return str(path)


class Books(models.Model):
    name = models.CharField(max_length=100,blank=False)
    name_slug = models.SlugField(blank=True, null=True, editable=False)
    title = models.CharField(max_length=256,blank=False)
    author_name = models.ForeignKey(Celebrity, null=True, on_delete=models.DO_NOTHING)
    description = models.TextField(null=True, blank=True)
    series = models.ForeignKey(Series, on_delete=models.CASCADE, null=True, blank=True)
    categories = models.ManyToManyField('Categories', blank=True)
    sub_categories = models.ManyToManyField('SubCategory', blank=True)
    ISBN = models.CharField(max_length=100,blank=True)
    amazonlink = models.URLField(default='https://amzn.to/3MquoAM')
    dateOfPublish = models.DateField(null=True)

    def __str__(self):
        return f'{self.name}' 
    
    def save(self, *args, **kwargs):
        if self.name:
            self.name_slug = slugify(self.name.upper())
        if self.pk is None and Books.objects.filter(name_slug=self.name_slug).exists():
            raise ValidationError("Name must be unique (case-insensitive).")
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        path = reverse('book-detail', args=[self.name_slug])
        return str(path)

 
def get_upload_path(instance, filename):
    field_value = instance.book.name
    # date_time = timezone.now().strftime('%Y/%m/%d')
    filename = os.path.basename(filename)
    return f'media/Books/{field_value}/{filename}'


class BookImages(models.Model):
    book = models.ForeignKey( "Books", on_delete=models.CASCADE)
    image = models.FileField(upload_to=get_upload_path, blank=True)


class FqBooks(models.Model):
    book = models.ForeignKey( "Books", on_delete=models.CASCADE)
    question = models.TextField(null=True, blank=True)
    answer = models.TextField(null=True, blank=True)

class FqSeries(models.Model):
    book = models.ForeignKey( "Series", on_delete=models.CASCADE)
    question = models.TextField(null=True, blank=True)
    answer = models.TextField(null=True, blank=True)

# class Rating(models.Model):
#     name = models.CharField(max_length=100,blank=False)
#     rating = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
#     book = models.ForeignKey( "Books", on_delete=models.CASCADE)

#     def __str__(self):
#         return f'{self.name}' 


class ContactForm(models.Model):
    name = models.CharField(max_length=100,blank=False)
    email = models.CharField(max_length=100,blank=False)
    subject = models.CharField(max_length=100,blank=False)
    message = models.TextField(max_length=500,blank=False)

    def __str__(self):
        return f'{self.name}' 

Books/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Q
from django.db.models import Count
from django.views.decorators.csrf import csrf_protect
from django.db.models.functions import Length
import wikipedia

from .models import SubCategory, Categories, Books, ContactForm, Series
from Celebrity.models import Celebrity
from Recommend.models import Recommend
from utils.common_function import create_json_for_list_book, create_json_for_book_Detail, create_json_for_categories, create_json_for_subcategories, get_json_for_home, create_json_for_series_Detail, create_json_for_list_series
# # Create your views here.


def home(request):
    peoples = Celebrity.objects.annotate(
        count=Count('celebritys')).order_by('-count')[:4]
    categories = Categories.objects.annotate(book_count=Count('books')).values(
        'name', 'book_count', 'name_slug').order_by('-book_count')[:4]
    books = Books.objects.annotate(recommendation_count=Count(
        'books')).order_by('-recommendation_count')[:3]
    keywords = 'read recommend'
    platform = []
    for people in peoples:
        social = ['#', '#', '#']
        for socialplatform in people.socialplatform_set.all():
            if socialplatform.name == "FACEBOOK":
                social[0] = socialplatform.link
            elif socialplatform.name == "TWITTER":
                social[1] = socialplatform.link
            elif socialplatform.name == "INSTAGRAM":
                social[2] = socialplatform.link
        platform.append(social)
        keywords = keywords + ', books recommend by ' + people.name
    peoples = zip(peoples, platform)

    for book in books:
        keywords = keywords + ', ' + book.name + " book"

    for category in categories:
        keywords = keywords + ', best books on ' + \
            category.get('name')

    json_website = get_json_for_home()

    data = {
        "peoples": peoples,
        "categories": categories,
        "books": books,
        "platform": platform,
        "keywords": keywords,
        'jsonWebsite': json_website
    }
    return render(request, 'home.html', data)


def categories(request):
    categories = Categories.objects.annotate(book_count=Count('books'), subCategory_count=Count('subcategory')).values(
        'name', 'book_count', 'name_slug', 'subCategory_count').order_by('-book_count')
    keywords = 'read recommend'
    json = create_json_for_categories(categories)
    keywords = keywords + ', best books on categories'
    data = {
        "categories": categories,
        "keywords": keywords,
        'jsonCategories': json
    }
    return render(request, 'categories.html', data)


def subCategories(request, name):
    books_list = []
    category = Categories.objects.filter(name_slug = name)
    subCategories = SubCategory.objects.filter(Category__name_slug=name)
    for subCategory in subCategories:
        books = Books.objects.filter(Q(categories__name_slug=name) & Q(sub_categories__name=subCategory.name)).values(
            'name', 'name_slug', 'title')
        books_list.append(books)

    remainingBooks = Books.objects.filter(Q(categories__name_slug=name) & Q(sub_categories__isnull=True)).values(
        'name', 'name_slug', 'title')
    books_list.append(remainingBooks)
    keywords = 'read recommend'
    json = create_json_for_subcategories(category[0])
    for subcategory in subCategories:
        keywords = keywords + ', best books on ' + \
            subcategory.name
    data = {
        "category" : category[0],
        "subCategories": subCategories,
        "books_list" : books_list,
        "keywords": keywords,
        'jsonCategories': json
    }
    return render(request, 'subCategories.html', data)


def privacyPolicy(request):
    return render(request, 'privacyPolicy.html')


def series(request):
    categories = request.GET.get('categories', None)
    keyword = request.GET.get('keyword', None)
    series = Series.objects.annotate(count=Count('books')).order_by('-count')

    if categories is not None and len(categories) > 0:
        categories = categories.split(",")
        series = series.filter(categories__name_slug__in=categories)
    if keyword is not None and len(keyword) > 0:
        series = series.filter(name__icontains=keyword)

    categories_list = Categories.objects.all().order_by(Length('name').asc())

    json_list = create_json_for_list_series(series)

    keywords = 'read recommend, series in order'

    data = {
        "series": series,
        'keywords': keywords,
        "categories": categories_list,
        'jsonList': json_list
    }

    return render(request, 'series.html', data)


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        contact = ContactForm.objects.create(
            name=name, email=email, subject=subject, message=message)
        if contact:
            data = {
                "submitted": "yes"
            }
            return render(request, 'contact.html', data)
    data = {
        "submitted": "no"
    }

    return render(request, 'contact.html', data)


def about(request):
    return render(request, 'about.html')


def search(request, keyword):
    keyword = keyword.replace("-", " ")
    celebrity_ids = Recommend.objects.values_list("Celebrity_id").distinct()
    peoples = Celebrity.objects.filter(
        id__in=celebrity_ids, name__icontains=keyword)
    people_count = len(peoples)

    author_ids = Books.objects.values_list("author_name_id").distinct()
    authors = Celebrity.objects.filter(
        id__in=author_ids, name__icontains=keyword)
    author_count = len(authors)

    books = Books.objects.filter(name__icontains=keyword)
    book_count = len(books)

    series = Series.objects.filter(name__icontains=keyword)
    series_count = len(series)

    total = people_count + author_count + book_count + series_count
    data = {
        "keyword": keyword,
        "peoples": peoples,
        "people_count": people_count,
        "authors": authors,
        "author_count": author_count,
        "books": books,
        "book_count": book_count,
        "series": series,
        "series_count": series_count,
        "total": total
    }
    return render(request, 'search.html', data)


@csrf_protect
def globalSearch(request):
    url = '/search/'
    if request.method == 'POST':
        keyword = request.POST['keyword']
        keyword = keyword.replace(' ', '-')
        url = url + keyword

    return redirect(url)


def get_sub_category(request, category_id):
    category_id = [] if category_id == "null" else category_id.split(",")
    subcategories = SubCategory.objects.filter(
        Category_id__in=category_id).distinct()
    response_data = [
        {'id': subcategory.id, 'name': subcategory.name}
        for subcategory in subcategories
    ]

    return JsonResponse(response_data, safe=False)


def books(request):
    categories = request.GET.get('categories', None)
    keyword = request.GET.get('keyword', None)
    books = Books.objects.annotate(count=Count('books')).order_by('-count')

    if categories is not None and len(categories) > 0:
        categories = categories.split(",")
        books = books.filter(categories__name_slug__in=categories)
    if keyword is not None and len(keyword) > 0:
        books = books.filter(name__icontains=keyword)

    categories_list = Categories.objects.all().order_by(Length('name').asc())

    json_list = create_json_for_list_book(books)

    keywords = 'read recommend, books'

    data = {
        "books": books,
        'keywords': keywords,
        "categories": categories_list,
        'jsonList': json_list
    }

    return render(request, 'books.html', data)


@csrf_protect
def filterBooks(request):
    url = '/books?'
    if request.method == 'POST':
        keyword = ''
        categories = []
        for key in request.POST:
            if key == 'keyword':
                keyword = 'keyword=' + request.POST[key]
            elif key != 'csrfmiddlewaretoken':
                categories.append(key)
        if len(keyword) > 0:
            url = url + keyword
        if len(categories) > 0:
            url = url + '&categories=' + ','.join(categories)

    return redirect(url)


@csrf_protect
def filterSeries(request):
    url = '/series?'
    if request.method == 'POST':
        keyword = ''
        categories = []
        for key in request.POST:
            if key == 'keyword':
                keyword = 'keyword=' + request.POST[key]
            elif key != 'csrfmiddlewaretoken':
                categories.append(key)
        if len(keyword) > 0:
            url = url + keyword
        if len(categories) > 0:
            url = url + '&categories=' + ','.join(categories)

    return redirect(url)


def bookDetail(request, name):

    book = Books.objects.filter(name_slug__iexact=name).annotate(
        count=Count('books')).order_by('-count')
    if book.first():
        book = book[0]
    else:
        return redirect("/books")
    recommend = Recommend.objects.filter(book=book)
    celeberity_ids = []
    for recom in recommend:
        celeberity_ids.append(recom.Celebrity_id)
    peoples = Celebrity.objects.annotate(
        count=Count('celebritys')).order_by('-count')
    peoples = peoples.filter(id__in=celeberity_ids)
    keywords = 'read recommend, '
    keywords = keywords + book.name + ' book'
    platform = []
    for people in peoples:
        social = ['#', '#', '#']
        for socialplatform in people.socialplatform_set.all():
            if socialplatform.name == "FACEBOOK":
                social[0] = socialplatform.link
            elif socialplatform.name == "TWITTER":
                social[1] = socialplatform.link
            elif socialplatform.name == "INSTAGRAM":
                social[2] = socialplatform.link

templates/seriesDetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Series {{series.name}} in Order ({{ series.count }} Books Series) : Read Recommend{% endblock %}
{% block extra_head %}
<link rel="icon" type="image/png" href="/static/img/favicon.ico">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">


<link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Template Stylesheet -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript"
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="{% static 'lib/wow/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/easing/easing.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Template Javascript -->
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>


<meta name="description" property="og:description" content="{{description}}">
<meta name="keywords" content="{{keywords}}">
<meta property="og:title" content="Series {{series.name}} in Order ({{ series.count }} Books Series): Read Recommend">
<meta property="og:description" content="{{description}}">
<meta property="og:url" content="readrecommend.com{{ request.get_full_path }}">
<meta property="website:tag" content="read recommend, series, {{series.name}}">

{% load render_json_ld from json_ld %}
{% render_json_ld jsonSeriesList %}

{% endblock %}
{% block content %}

<!-- Spinner Start -->
<div id="spinner"
    class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->

<!-- Header Start -->
<div class="container-fluid header bg-white p-0">
    <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
        <div class="col-md-6 p-5 mt-lg-5">
            <h1 class="display-5 animated fadeIn mb-4">{{series.name | lower | title}} in Order ({{ series.count }} Books Series)</h1>
            <nav aria-label="breadcrumb animated fadeIn">
                <ol class="breadcrumb text-uppercase">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'series' %}">Series</a></li>
                    <li class="breadcrumb-item text-body active" aria-current="page">{{series.name}} in Order</li>
                </ol>
            </nav>
        </div>
        <div class="col-md-6 animated fadeIn">
            <img class="img-fluid" src="https://flowbite.s3.amazonaws.com/docs/jumbotron/conference.jpg"
                alt="read-recommend cover image" loading="lazy">
        </div>
    </div>
</div>
<!-- Header End -->

<!-- About Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 align-items-center">
            <div class="col-lg-5 wow fadeIn" data-wow-delay="0.1s">
                <div class="about-img position-relative overflow-hidden p-5 pe-0">
                    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner w-60">
                            
                          <div class="carousel-item active" data-bs-interval="1000">
                            <img src="{% if series.image %} {{series.image.url}} {% else %} {% static 'img/read-recommend-logo-2.png' %} {% endif %}" class="d-block w-60" alt="{{series.name}} image-0">
                          </div>

                          {% for seriesImage in seriesImages %}
                          <div class="carousel-item" data-bs-interval="1000">
                            <img src="{% if seriesImage %} {{seriesImage}} {% else %} {% static 'img/read-recommend-logo-2.png' %} {% endif %}" class="d-block w-60" alt="{{series.name}} image-{{ forloop.counter }}">
                          </div>
                          {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </button>
                      </div>
                </div>
            </div>
            <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                <h2 class="mb-4">{{series.name | lower | title}} in Order</h2>
                <a href="{% url 'author-detail'  series.author_name.name_slug %}" class="text-center">
                    <div class="d-flex align-items-center">
                        {% if series.author_name.image %}
                        <img class="img-fluid flex-shrink-0 rounded" src="{{series.author_name.image.url}}"
                            style="width: 45px; height: 45px;" alt="{{series.author_name.name_slug}} Avtar" loading="lazy">
                        {% endif %}
                        <div class="ps-3">
                            <h6 class="fw-bold mb-1">{{ series.author_name.name|lower|title}}</h6>
                            <small>{{ series.author_name.professions.all |join:", "}}</small>
                        </div>
                    </div>
                </a>

                <p class="mb-4 py-3">{{series.description |truncatewords:50}}</p>
                <p><i class="fa fa-check text-primary me-3"></i>{{ series.count }} Books Series</p>
                {% if series.categories.all %}
                <p><i class="fa fa-check text-primary me-3"></i> {{series.categories.all |join:", " }}</p>
                {% endif %}
                <div class="alert alert-success" role="alert">
                    <small>
                    As an Amazon Associate, we earn money from purchases made through links in this page.
                </small>
                </div>
                <a onclick="window.open('{{wikipedia}}')" class="btn btn-outline-dark py-2 px-2">Wikipedia</a>
            </div>
        </div>
    </div>
</div>
<!-- About End -->

<div class="container-xxl py-5">
    <div class="row g-0 justify-content-center flex-column-reverse flex-md-row">
        <div class="col-md-4 animated fadeIn">
            <div class="text-start mx-auto mb-5 wow slideInLeft" data-wow-delay="0.1s"">
                <div class=" wow fadeInRight animated">
                <div class="text-start mx-auto mb-5 wow slideInLeft" data-wow-delay="0.1s">
                    <h3 class="mb-3">You may also like</h3>
                    <p>Series from similar Categories</p>

                    {% for recom in recomSeries %}
                    <div class="py-3">
                        <a href="{% url 'series-detail' recom.name_slug %}">
                            <div class="d-flex align-items-center">
                                {% if recom.image %}
                                <img class="img-fluid flex-shrink-0 rounded" src="{{recom.image.url}}"
                                    style="width: 45px; height: 45px;" alt="{{recom.name_slug}} Avtar">
                                {% endif %}
                                <div class="ps-3">
                                    <h6 class="fw-bold mb-1">{{ recom.name|lower|title}}</h6>
                                    <small>{{ recom.count }} Books</small>
                                </div>

                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-8 animated fadeIn">
        <div class="row g-3">
            {% for bookrecom in books %}
            <div class="col-lg-4 col-md-6 wow fadeInUp book-card" data-wow-delay="0.1s">
                <div class="property-item rounded overflow-hidden">
                    <div class="position-relative overflow-hidden">
                        <div class="text-center">
                            {% for bookimage in bookrecom.bookimages_set.all|slice:":1" %}
                            <a href="{{bookrecom.amazonlink}}" target="_blank"><img class="img-fluid" src="{{bookimage.image.url}}" alt="{{ bookrecom.name }}"
                                    style="padding-top: 10px; border-radius: 10px; width: 350px; height: 400px;" loading="lazy"></a>
                            {% endfor %}
                        </div>

                        <div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">
                            {{ bookrecom.dateOfPublish }} Published</div>
                    </div>
                    <div class="p-4 pb-0">
                        <a class="d-block h5 mb-3 text-center" href="">{{bookrecom.name|lower|title}}</a>
                        <p class="text-center py-2">
                            {% if bookrecom.categories.all %}
                            <i class="fa fa-map-marker-alt text-primary me-2">
                            </i>
                            {{bookrecom.categories.all |join:", " }}
                            {% endif %}
                        </p>
                        <a href="{% url 'author-detail' bookrecom.author_name.name_slug %}" class="text-center">
                            <div class="d-flex align-items-center">
                                {% if bookrecom.author_name.image %}
                                <img class="img-fluid flex-shrink-0 rounded" src="{{bookrecom.author_name.image.url}}"
                                    style="width: 45px; height: 45px;"
                                    alt="{{bookrecom.book.author_name.name_slug}} Avtar" loading="lazy">
                                {% endif %}
                                <div class="ps-3">
                                    <h6 class="fw-bold mb-1">{{ bookrecom.author_name.name|lower|title}}</h6>
                                    <small>{{ bookrecom.author_name.professions.all |join:", "}}</small>
                                </div>

                            </div>
                        </a>
                    </div>
                    <div class="d-flex py-3">
                        <small class="flex-fill text-center py-2">
                            <a class="btn btn-outline-dark"
                            href="{% url 'book-detail' bookrecom.name_slug %}">View Details</a>
                        </small>

                        <small class="flex-fill text-center py-2">
                            <a class="btn btn-outline-primary active" data-bs-toggle="pill" style="color: white;"
                                href="{{bookrecom.amazonlink}}" onclick="window.open('{{book.amazonlink}}')">View
                                on
                                Amazon</a>
                        </small>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="text-center mx-auto mb-5 wow slideInLeft py-3" data-wow-delay="0.1s">
            <h2 class="mb-3">FAQ</h2>
        </div>

        <div class="accordion accordion-flush py" id="accordionFlushExample">
            {% for seriesFQ in series.fqseries_set.all %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        #{{ forloop.counter }} : {{ seriesFQ.question }}
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                    data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body"> {{ seriesFQ.answer }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

{% endblock %}

templates/tmp.html
abcs